### ISSUE TITLE
Deleting dataset causes error (Google Colab)

### ISSUE THREAD

**Issue by hetzukara** [yu4u/noise2noise#54]
Hi, im was training my ai and I run the ai on google colab, I have some images wich is clean image and dirty image i was curious about replacing my dataset with new image, before im replacing the file its just works fine and when Im replaced with new dataset and this problem comes up
```
Traceback (most recent call last):
  File "noise2noise/test_model.py", line 70, in <module>
    main()
  File "noise2noise/test_model.py", line 47, in main
    h, w, _ = image.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```
Im not disappointed with the result but this problem was kinda easy to fix by my self like reset the runtime the problem was gone. Any clues?

**Comment by ghost** [comment]
Check your images, it must be 24 bit depth

**Comment by playbyan1453** [comment]
Yes, after I checked the image have 24 bit depth, but the problem is after I'm trained my ai and change the dataset to the new one the error happened. And the error happens while im testing the dataset with new image. Because im wanted to make my own denoiser for my renders.

Here some of examples:
![glass_material](https://user-images.githubusercontent.com/62523229/100663061-52a44c00-3388-11eb-8601-e5c75c7b44aa.png) ![glass_sphere](https://user-images.githubusercontent.com/62523229/100663421-d2cab180-3388-11eb-92cb-a0648ad8c1ca.png) ![cornell_box](https://user-images.githubusercontent.com/62523229/100663527-03125000-3389-11eb-911b-09cc016468b7.png)

I also make the low sampling dataset so the ai knows what to do

**Comment by hetzukara** [comment]
Yes, after I checked the image have 32 bit depth, so im trying to make my own denoiser let me try change it to 24 bit depth.
Edit : I still have same problem untill now
